server:
  port: 8086

spring:
  application:
    name: payment-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payment_service}
    username: ${SPRING_DATASOURCE_USERNAME:payment_user}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:19092}

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: payment-service
      auto-offset-reset: earliest
      enable-auto-commit: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

    listener:
      ack-mode: manual

    properties:
      allow.auto.create.topics: true

jwt:
  issuer: identity-service
  signerKey: ${JWT_SIGNER_KEY}

app:
  saga:
    topics:
      payment-commands: payment.commands
      payment-events: payment.events

  outbox:
    enabled: true
    poll-ms: 1000
    batch-size: 100
    max-retry: 50
    use-skip-locked: true

logging:
  level:
    com.dang.paymentservice: DEBUG
