server:
  port: 8084

spring:
  application:
    name: order-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_service}
    username: ${SPRING_DATASOURCE_USERNAME:order_user}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: OrderServicePool
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:19092}

    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

    listener:
      ack-mode: manual

    properties:
      allow.auto.create.topics: true

logging:
  level:
    com.dang.orderservice: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  issuer: identity-service
  signerKey: ${JWT_SIGNER_KEY}

app:
  messaging:
    kafka:
      enabled: true

  saga:
    topics:
      inventory-commands: inventory.commands
      inventory-events: inventory.events
      payment-commands: payment.commands
      payment-events: payment.events

  outbox:
    enabled: true
    poll-ms: 1000
    batch-size: 100
    max-retry: 50
    use-skip-locked: true
