apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
  name: inventory-service
  namespace: ecommerce
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: inventory-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-21T05:13:05+07:00"
      labels:
        app: inventory-service
    spec:
      containers:
        - env:
            - name: SERVER_PORT
              value: "8085"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://pg-postgresql:5432/inventory_service
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: ecommerce-db-secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: ecommerce-db-secret
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-kafka-bootstrap:9092
            - name: JWT_SIGNER_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_SIGNER_KEY
                  name: identity-jwt
            - name: APP_MESSAGING_KAFKA_ENABLED
              value: "true"
          image: inventory-service
          imagePullPolicy: IfNotPresent
          name: inventory-service
          ports:
            - containerPort: 8085
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
