apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - identity-deploy.yaml
  - identity-svc.yaml

  - product-deploy.yaml
  - product-svc.yaml

  - customer-deploy.yaml
  - customer-svc.yaml

  - order-deploy.yaml
  - order-svc.yaml

  - payment-deploy.yaml
  - payment-svc.yaml

  - inventory-deploy.yaml
  - inventory-svc.yaml

  - ecommerce-ingress.yaml
