apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - ../../base

images:
  - name: identity-service
    newName: ghcr.io/dang2k5/identity-service
    newTag: latest

  - name: product-service
    newName: ghcr.io/dang2k5/product-service
    newTag: latest

  - name: customer-service
    newName: ghcr.io/dang2k5/customer-service
    newTag: latest

  - name: order-service
    newName: ghcr.io/dang2k5/order-service
    newTag: latest

  - name: payment-service
    newName: ghcr.io/dang2k5/payment-service
    newTag: latest

  - name: inventory-service
    newName: ghcr.io/dang2k5/inventory-service
    newTag: latest
